const StoreActionTypes = {
    SIGN_UP_STORE_START: 'SIGN_UP_STORE_START',
    SIGN_UP_STORE_SUCCESS: 'SIGN_UP_STORE_SUCCESS',
    SIGN_UP_STORE_FAILURE: 'SIGN_UP_STORE_FAILURE',
    GET_ALL_STORES_LIST_START: 'GET_ALL_STORES_LIST_START',
    GET_ALL_STORES_LIST_SUCCESS: 'GET_ALL_STORES_LIST_SUCCESS',
    GET_ALL_STORES_LIST_FAILURE: 'GET_ALL_STORES_LIST_FAILURE',
    UPDATE_STORE_PROFILE_START: 'UPDATE_STORE_PROFILE_START',
    UPDATE_STORE_PROFILE_SUCCESS: 'UPDATE_STORE_PROFILE_SUCCESS',
    UPDATE_STORE_PROFILE_FAILURE: 'UPDATE_STORE_PROFILE_FAILURE',
};

export default StoreActionTypes;