const AuthActionTypes = {
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    FORGOT_PASSWORD_START: 'FORGOT_PASSWORD_START',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    RESET_PASSWORD_START: 'RESET_PASSWORD_START',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_UP_CLIENT_START: 'SIGN_UP_CLIENT_START',
    SIGN_UP_CLIENT_SUCCESS: 'SIGN_UP_CLIENT_SUCCESS',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    NO_USER_FOUND: 'NO_USER_FOUND',
    VALIDATE_RESET_TOKEN_START: 'VALIDATE_RESET_TOKEN_START',
    VALIDATE_RESET_TOKEN_SUCCESS: 'VALIDATE_RESET_TOKEN_SUCCESS',
    VALIDATE_RESET_TOKEN_FAILURE: 'VALIDATE_RESET_TOKEN_FAILURE',
    UPDATE_USER_PROFILE_START: 'UPDATE_USER_PROFILE_START',
    UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
    UPDATE_USER_PROFILE_FAILURE: 'UPDATE_USER_PROFILE_FAILURE',
};

export default AuthActionTypes;