const UserActionTypes = {
    SIGN_UP_CLIENT_START: 'SIGN_UP_CLIENT_START',
    SIGN_UP_CLIENT_SUCCESS: 'SIGN_UP_CLIENT_SUCCESS',
    SIGN_UP_CLIENT_FAILURE: 'SIGN_UP_CLIENT_FAILURE',
    GET_ALL_CLIENTS_LIST_START: 'GET_ALL_CLIENTS_LIST_START',
    GET_ALL_CLIENTS_LIST_SUCCESS: 'GET_ALL_CLIENTS_LIST_SUCCESS',
    GET_ALL_CLIENTS_LIST_FAILURE: 'GET_ALL_CLIENTS_LIST_FAILURE',
    UPDATE_USER_PROFILE_START: 'UPDATE_USER_PROFILE_START',
    UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
    UPDATE_USER_PROFILE_FAILURE: 'UPDATE_USER_PROFILE_FAILURE',
};

export default UserActionTypes;